# Generated by Django 2.1.3 on 2018-11-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0003_card_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='business_value',
        ),
        migrations.RemoveField(
            model_name='card',
            name='list',
        ),
        migrations.RemoveField(
            model_name='card',
            name='story_points',
        ),
    ]
